theme: jekyll-theme-cayman
title: Diseño y desarrollo de sistemas seguros
description: Portafolio de aprendizaje de la asignatura "Diseño y desarrollo de sistemas seguros"
show_downloads: false
github:
  is_project_page: false
